# Generated by Django 5.0.6 on 2024-06-14 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.TextField(max_length=100, null=True)),
                ('price', models.FloatField(null=True)),
                ('discription', models.TextField(max_length=100, null=True)),
                ('image', models.ImageField(null=True, upload_to='products')),
            ],
        ),
    ]
