# Generated by Django 5.0.6 on 2024-08-12 07:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0005_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer_details',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='product_details',
            new_name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='ordered_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
