# Generated by Django 5.0.6 on 2024-06-07 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.TextField(db_column='first name', max_length=100, null=True)),
                ('lname', models.TextField(max_length=100, null=True)),
                ('email', models.TextField(max_length=100, null=True)),
                ('mobile', models.BigIntegerField(null=True)),
                ('password', models.TextField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.TextField(db_column='first name', max_length=100, null=True)),
                ('lname', models.TextField(max_length=100, null=True)),
                ('email', models.TextField(max_length=100, null=True)),
                ('mobile', models.BigIntegerField(null=True)),
                ('password', models.TextField(max_length=100, null=True)),
            ],
        ),
    ]
