# Generated by Django 5.0.6 on 2024-06-15 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='lname',
            new_name='adress',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='fname',
            new_name='hname',
        ),
        migrations.AddField(
            model_name='seller',
            name='image',
            field=models.ImageField(null=True, upload_to='seller'),
        ),
    ]
