# Generated by Django 5.0.6 on 2024-06-15 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_rename_lname_seller_adress_rename_fname_seller_hname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='image',
            field=models.ImageField(null=True, upload_to='restaurant'),
        ),
    ]
