# Generated by Django 5.0.6 on 2024-07-02 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_seller_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='adress',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
