# Generated by Django 5.0.6 on 2024-07-04 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_customer_adress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='adress',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='adress',
            new_name='address',
        ),
    ]
